---
datasource:
  jpa:
    driver: com.mysql.cj.jdbc.Driver
    username: test
    password: test123
    url: jdbc:mysql://127.0.0.1:3306/test
server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true